name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "00 19 * * 6"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t shiny-docker-demo . 

  push:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Push the Docker image to a predefined repository
      run: docker build -t shiny-docker-demo . 
